### PR TITLE
Widget hooks for dashboard

### PR DESCRIPTION
**Pull request by fre2mansur**

### CODE REVIEW

**Comment by dftd** [comment]
@fre2mansur Pretty sure you need to target develop branch for it to be merged.

**Comment by fre2mansur** [comment]
> @fre2mansur Pretty sure you need to target develop branch for it to be merged.

Thank you changed

**Comment by navjottomer** [comment]
I am sure you were wondering, why this request is not merged yet. Have some changes in another local branch, where I am making changes to backend. It will be considered after merging those changes.

**Comment by dftd** [comment]
> I am sure you were wondering, why this request is not merged yet. Have some changes in another local branch, where I am making changes to backend. It will be considered after merging those changes.

Ok, excited to see what you'll add to backend. 👀

**Comment by navjottomer** [comment]
> > I am sure you were wondering, why this request is not merged yet. Have some changes in another local branch, where I am making changes to backend. It will be considered after merging those changes.
> 
> Ok, excited to see what you'll add to backend. 👀

admin-peek

work in progress.

**Pull request closed without merging**
