### PR TITLE
Before user recover hook

### PR DESCRIPTION
**Pull request by webmods-croatia**
https://github.com/mindstellar/Osclass/issues/195

### CODE REVIEW

**Comment by webmods-croatia** [comment]
@navjottomer What do I need to fix here?

**Comment by navjottomer** [comment]
You should not have included the bender related changes in this pull request.

**Comment by webmods-croatia** [comment]
> You should not have included the bender related changes in this pull request.

I must have selected it by mistake...

**Comment by webmods-croatia** [comment]
@navjottomer Same here.

**Pull request merged**
