### PR TITLE
Cookies & GDPR

### PR DESCRIPTION
**Pull request by patriksh**
Related issues: https://github.com/mindstellar/Osclass/issues/211 https://github.com/mindstellar/Osclass/issues/245

How do I add new email templates so they work properly with updating Osclass?

How to disable sanitization on form labels so I can add <a> tags to terms & conditions / privacy policy?

Do I add additional columns to both user and item table regarding https://github.com/mindstellar/Osclass/issues/269? We already have b_show_email for item, do I add b_show_phone? What about showing the same data on public profile?

### CODE REVIEW

**Comment by navjottomer** [comment]
@alastairR 
> I don't know if it's any use, but I merged a GDPR cookie popup plugin with an old GDPR osclass plugin to create a new plugin that I just published yesterday: https://github.com/alastairR/osclass-gdpr
> 
> I suspect that other than a core option in listing edit to hide a phone number, like the email hide, the rest of the GDPR stuff should be in an open source plugin.

That's great. 
I was sceptical about merging this PR in our beta as I don't have time to test all the changes. I was thinking of merging it after 5.1 but a plugin is much better.

@dftd 
> How do I add new email templates so they work properly with updating Osclass?
> 
> How to disable sanitization on form labels so I can add tags to terms & conditions / privacy policy?
The current option is to add DAO methods for inserting email templates.
If you're using FormInputs class, it doesn't use any sanitization on input labels.

**Comment by navjottomer** [comment]
> I thibk this should surely be a part of Osclass core, doesn't matter if it won't make it to 5.1 release.

We'll see about it, for meantime, a plugin is already available so that's good for us.
> 
> I use FormInputs class, check this:
> 
> https://github.com/mindstellar/Osclass/blob/2ba1754e2a3b0f80beda49d0adf3fe7e8e0f1d9b/oc-includes/osclass/classes/form/base/FormInputs.php#L381

Yup, it's escaping but you said sanitization got me confused. Anyway, it will only escape not remove any tag. 

> Also regarding checkboxes, what classes do I put on the inputs, do I make it Bender compatible out-of-the-box? Ideally themes would implenent checkboxes themselves and remove the default hooks.

Keep the default and it'll work with bender. If theme developers want to change classes then they can just extend the Form classes, override the properties and call the same method with extended class, that's super easy for them.

**Comment by dftd** [comment]
Oh, how come you merged it... I gotta add some fixes.
Do I make a new PR?

**Comment by navjottomer** [comment]
Oh I thought you fixed everything, make new PR I'll revert this.

**Comment by dftd** [comment]
@navjottomer Again having problems with escaping HTML.

If I use `sprintf(__('I agree with the <a href="%s">Privacy Policy</a>.'), osc_gdpr_privacy_page_url())` as label, it does get removed since label function is using `$this->escape::html($label)`.

**Comment by dftd** [comment]
No idea what's the best way to insert the new mail template. Do I hardcode a function for it and run it when upgrade DB is ran?
Do you think cookie notice should be translatable inside admin? And I save translations as JSON in preference? Or we just keep it as it is, so it can be translated in .po files.

**Pull request merged**
